name: Run blocklist checks


on:
workflow_dispatch:
schedule:
- cron: '0 2 * * *' # optional daily run at 02:00 UTC; edit or remove if you don't want schedules


jobs:
run-checks:
runs-on: ubuntu-latest
steps:
- name: Checkout repo
uses: actions/checkout@v4


- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.11'


- name: Install dependencies
run: python -m pip install --upgrade pip && pip install -r requirements.txt


- name: Run checks
env:
# Example: expose secrets referenced by checkers.json here.
VT_API_KEY: ${{ secrets.VT_API_KEY }}
ABUSEIPDB_KEY: ${{ secrets.ABUSEIPDB_KEY }}
run: |
mkdir -p outputs
python src/checker.py --urls data/urls.txt --checkers data/checkers.json --out outputs/results.json --report outputs/report.txt


- name: Upload results artifact
uses: actions/upload-artifact@v4
with:
name: blocklist-results
path: outputs/
