name: Run checks

on:
  workflow_dispatch:     # 👈 allows manual runs from the Actions tab
  push:                  # optional: runs on push to main
    branches: [ "main" ]
  schedule:              # optional: runs daily at midnight UTC
    - cron: "0 0 * * *"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run blocklist checks
        env:
          VT_API_KEY: ${{ secrets.VT_API_KEY }}
          ABUSEIPDB_KEY: ${{ secrets.ABUSEIPDB_KEY }}
          GSB_KEY: ${{ secrets.GSB_KEY }}
          URLSCAN_API_KEY: ${{ secrets.URLSCAN_API_KEY }}   # optional if added
          OTX_API_KEY: ${{ secrets.OTX_API_KEY }}           # optional if added
        run: |
          mkdir -p outputs
          python src/checker.py \
            --urls data/urls.txt \
            --checkers data/checkers.json \
            --out outputs/results.json \
            --report outputs/report.txt

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: outputs/*
          compression-level: 6   # default, can be 0–9
          overwrite: true        # replace artifact if exists
